package com.fet.db.oracle.pojo;
// Generated 2021/2/3 �U�� 04:24:52 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AalexMaster generated by hbm2java
 */
@Entity
@Table(name = "AALEX_MASTER")
public class AalexMaster implements java.io.Serializable {

	private String cono;
	private String conoStatus;
	private String iaStatus;
	private String test;

	public AalexMaster() {
	}

	public AalexMaster(String cono) {
		this.cono = cono;
	}

	public AalexMaster(String cono, String conoStatus, String iaStatus, String test) {
		this.cono = cono;
		this.conoStatus = conoStatus;
		this.iaStatus = iaStatus;
		this.test = test;
	}

	@Id

	@Column(name = "CONO", unique = true, nullable = false, length = 20)
	public String getCono() {
		return this.cono;
	}

	public void setCono(String cono) {
		this.cono = cono;
	}

	@Column(name = "CONO_STATUS", length = 20)
	public String getConoStatus() {
		return this.conoStatus;
	}

	public void setConoStatus(String conoStatus) {
		this.conoStatus = conoStatus;
	}

	@Column(name = "IA_STATUS", length = 20)
	public String getIaStatus() {
		return this.iaStatus;
	}

	public void setIaStatus(String iaStatus) {
		this.iaStatus = iaStatus;
	}

	@Column(name = "TEST", length = 20)
	public String getTest() {
		return this.test;
	}

	public void setTest(String test) {
		this.test = test;
	}

}
